// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sagvgkbmnwzlfrlrtwok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZ3Zna2Jtbnd6bGZybHJ0d29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzI2MzksImV4cCI6MjA3NDY0ODYzOX0.ncN7wLW5jutWiHnkLQ0f7prpjoR7lhsp72KEB_1ouJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});